apiVersion: v1
kind: PersistentVolume
metadata:
  name: maven-repo-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/mnt/data/m2"  # Bu, Kubernetes node'unda kalıcı bir dizin
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maven-repo-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
